### ISSUE TITLE
Projekt apk-fähig machen

### ISSUE THREAD

**Issue by Besteresis** [BP-28-FearVR/FearOfHeights#76]
### Beschreibung
Als Nutzer möchte ich, dass die Anwendung auch auf dem VR-Headset selber starten und laufen kann, sodass das VR-Headset nicht mit einem PC verbunden sein muss.

### Akzeptanzkriterien
- Die Anwendung ist als apk kompilierbar
- In der VR-Applikation gibt es keine Einbußung von Funktionalitäten im Vergleich zur Ausführung in Unity

**Comment by Sigma42** [comment]
wegenn Problem im neuen Branch https://github.com/BP-28-FearVR/FearOfHeights/tree/76a_project-apk-faehig(fix)
